name: finals
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  vector_graphics: ^1.1.11+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  vector_graphics_compiler: ^1.1.11+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - path: assets/photos/
    - path: assets/svgs/
      transformers:
        - package: vector_graphics_compiler