name: fitd25
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  timeago_flutter: ^3.7.0
  confetti: ^0.8.0
  devtools_app_shared: ^0.4.0
  web: ^1.1.1
  json_dynamic_widget: ^10.0.1
  firebase_auth: ^6.0.0
  collection: ^1.19.1
  clock: ^1.1.2
  fake_async: ^1.3.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - path: assets/photos/
    - path: assets/logos/