name: fitd25
description: "A set of tools to run a Flutter in the Dark event. This includes a challenger view, an admin view, and a show view for the audience."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  clock: ^1.1.2
  cloud_firestore: ^6.0.0
  collection: ^1.19.1
  confetti: ^0.8.0
  devtools_app_shared: ^0.4.0
  fake_async: ^1.3.3
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  gap: ^3.0.1
  intl: ^0.20.2
  json_dynamic_widget: ^10.0.2
  pointer_interceptor: ^0.10.1+2
  timeago_flutter: ^3.7.0
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  json_dynamic_widget_codegen: ^3.0.0
  lint: ^2.8.0

flutter:
  uses-material-design: true
  assets:
    - path: assets/photos/
    - path: assets/logos/