name: flutter_in_the_dark
description: "A set of tools to run a Flutter in the Dark event. This includes a challenger view, an admin view, and a show view for the audience."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  confetti: ^0.8.0
  devtools_app_shared: ^0.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  gap: ^3.0.1
  intl: ^0.20.2
  pointer_interceptor: ^0.10.1+2
  timeago_flutter: ^3.7.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.8.0

flutter:
  uses-material-design: true
  shaders:
    - shaders/burn.frag
